### PR TITLE
Feature/modelfileformat

### LINKED ISSUE #46: Extend Legacy format to enable clean tandem D models definition
This feature request is a step towards achieving a cleaner and testable implementation of the Tandem D feature discussed in #8 .

The proposed solution is a temporary extension of the legacy `Model_parms.txt` file format, before a complete redefinition of model parms and model_marginals files discussed in #32. 

The proposed solution relies on several ideas:

- the re-use of a dynamic Seq_type registry introduced in #15 and discussed in #8 
- the refactoring of the usage and definition of Gene_class originally discussed in Problem 1  [here](https://github.com/IGoR-immuno-stack/IGoR/issues/8#issuecomment-3854512155) and now tracked in #47  
- the dynamic definition of Seq_type ordering discussed in Problem 5  [here](https://github.com/IGoR-immuno-stack/IGoR/issues/8#issuecomment-3854512155)

### LINKED ISSUE #47: Refactor Gene_class and Seq_type usage
Based on discussions in #8 . The idea of this refactoring would be to make a clearer separation between Gene_class and Seq_type. This should facilitate the implementation of tandem Ds.

>  I think I have used Gene_class instead of Seq_type at different places, marked below with ❌ in the summary table below:
> 
> | Phase | Gene_class | Seq_type |
> |-------|-----------|----------|
> | **Alignment** | Determines alignment strategy (V/D/J) | Not used |
> | **Inference (Gene_choice)** | Determines which alignments to iterate | Identifies constructed sequence segment |
> | **Inference (Deletion)** | Determines which gene to delete from ❌ | Maps to Seq_type for offset updates |
> | **Inference (Insertion)** | Identifies junction (VD/DJ/VJ) ❌| Identifies insertion sequence segment |
> | **Inference (Dinucl)** | Determines which junctions to fill ❌| Accesses insertion sequences |
> | **Inference (Error Rate)** | Not used | Identifies segments to compare |
> | **Generation** | Determines what event generates | Identifies where to store result |
> | **Model Structure** | Organizes events in events_map ❌| Not used |
> 
> Here is the justification for each:
> - **Inference (Deletion)** -> should not care about the actual underlying "gene" (at least not in its current implementation), should only care about Seq_type, which identifies on which constructed sequence the deletion event should act.
> - **Inference (Insertion)** -> same reasoning + (VD_genes, DJ_genes, VJ_genes) don't make much sense semantically. 
> - **Inference (Dinucl)** -> same as previous + Here the Gene_class information has been used as a surrogate for an implicit tuple of  (Seq_type,Seq_side) in the implementation: identities of inserted nucleotides with a VD_genes class implicitly means insertion in the VD_ins_seq starting with the Five_prime (leftmost) nucleotide (using the last nucleotide of the constructed sequence on the left, i.e. the V_gene_seq). Conversely DJ_genes stands implicitly for (DJ_ins_seq, Three_prime), i.e. Process DJ insertions **backwards** (3' to 5') (from right to left).
> - **Model Structure** | Organizes events in events_map -> here the problem is much worse, because it means that events are not uniquely identifiable from the events_map for tandem Ds with the original Gene_class enum. Instead of a `unordered_map<tuple<Event_type, Gene_class, Seq_side>, shared_ptr<Rec_Event>>` we should probably have an `unordered_map<tuple<Event_type, Seq_type, Seq_side>, shared_ptr<Rec_Event>>`.
> 
> I think a proper fix would be to:
> 1. Nuke everything but V_gene, D_gene and J_gene in the Gene_class enum. This Gene_class enum will have for sole purpose to map events to actual genomic regions/alignements.
> 2. Change all Gene_class marked as ❌ above to use the new Seq_type registry. Small twist on **Inference (Dinucl)** discussed below in Problem 5.
> 
> I think this fits into the refactoring issue #7 as some of the proposed replacements would naturally help remove some switch statements. 
> 
> It also goes hand in hand with the update on model format proposed in #32 . Point of vigilance: the proposed solution would also require to add some Gene_class <-> (Seq_type, Seq_side) logic into the legacy format converter code.
>

### PR DESCRIPTION
**Pull request by ErwanDemairy**

### CODE REVIEW

File: src/igor/Core/Utils.h [hunk 1]
```diff
@@ -109,12 +109,12 @@ enum Seq_side { Five_prime = 0, Three_prime = 1, Undefined_side = 2 };
...
     D_gene = 2,
-    DJ_genes = 3,
+    DJ_genes = 3,   ///< LEGACY: junction class, kept for legacy file read/write only
     J_gene = 4,
-    VJ_genes = 5,
-    VDJ_genes = 6,
+    VJ_genes = 5,   ///< LEGACY: junction class, kept for legacy file read/write only
+    VDJ_genes = 6,  ///< LEGACY: junction class, kept for legacy file read/write only
     Undefined_gene = 7
 };
```
Comment (qmarcou) [inline src/igor/Core/Utils.h:135]: For clarity I think it would be best to keep a clean `Gene_class`, with legacy enum members dropped, as in #53, and have a Gene_class_legacy for conversion purposes only.

File: src/igor/Core/Deletion.cpp [hunk 2]
```diff
@@ -190,9 +231,11 @@ void Deletion::iterate(
     //unordered_map<Rec_Event_name,int> base_index_map_copy(base_index_map);
     //unordered_map<Seq_type,vector<int>*> mismatches_lists_copy (mismatches_lists);
 
-    switch ((*this).event_class) {
+    const Seq_type target_seq_type = get_deletion_target_seq_type(this->event_class);
```
Comment (qmarcou) [inline src/igor/Core/Deletion.cpp]: should be (immutable?) initialized at construction time not fetched in the hot loop

Comment (qmarcou) [reply src/igor/Core/Deletion.cpp]: already addressed in a commit in #53

File: src/igor/Core/Deletion.h [hunk 3]
```diff
@@ -77,7 +77,16 @@ class CORE_EXPORT Deletion : public Rec_Event
...
+            const Events_map &,
+            Safety_bool_map &, Mismatch_vectors_map &, double &, double &);
+
+    inline void
+    iterate(double &, Downstream_scenario_proba_bound_map &, const std::string &, const Int_Str &, Index_map &,
+            const std::unordered_map<Rec_Event_name, std::vector<std::pair<std::shared_ptr<const Rec_Event>, int>>> &,
+            std::shared_ptr<Next_event_ptr> &, Marginal_array_p &, const Marginal_array_p &,
+            const std::unordered_map<Gene_class, std::vector<Alignment_data>> &, Seq_type_str_p_map &,
+            Seq_offsets_map &, std::shared_ptr<Error_rate> &, std::map<size_t, std::shared_ptr<Counter>> &,
+            const std::unordered_map<std::tuple<Event_type, Seq_type, Seq_side>, std::shared_ptr<Rec_Event>> &,
```
Comment (qmarcou) [inline src/igor/Core/Deletion.h]: Duplication, see #53

File: src/igor/Core/Dinuclmarkov.cpp [hunk 4]
```diff
@@ -26,8 +26,40 @@
...
+        return { { VJ_ins_seq, V_gene_seq, Five_prime, false } };
+    case VDJ_genes:
+        return {
+            { VD_ins_seq, V_gene_seq, Five_prime, false },
+            { DJ_ins_seq, J_gene_seq, Five_prime, true },
+        };
+    default:
+        return {};
+    }
+}
```
Comment (qmarcou) [inline src/igor/Core/Dinuclmarkov.cpp]: Updated in #53

File: src/igor/Core/Dinuclmarkov.cpp [hunk 5]
```diff
@@ -97,74 +131,64 @@ void Dinucl_markov::iterate(
...
-        data_seq_substr =
-                query.int_sequence.substr(scenario.get_offset(V_gene_seq, Five_prime) + previous_seq_size, vj_seq.size());
-
-        previous_nt_str = previous_seq.back();
-        iterate_common(vj_realizations_indices, previous_nt_str, vj_seq, model.model_parameters);
-
-        exploration.downstream_proba_map.set_value(VJ_ins_seq, 1.0, memory_layer_proba_map_junction_1);
-    }
-    if (!correct_class) {
+    const auto traversal_specs = get_dinucl_traversal_specs(event_class);
```
Comment (qmarcou) [inline src/igor/Core/Dinuclmarkov.cpp]: should happen at construction/initialization

File: tst/igor/entropy_test_helpers.h [hunk 6]
```diff
@@ -47,7 +47,7 @@ struct EventInfo
     bool is_dinuc_markov; ///< skip empirical check for DinucMarkov
     std::vector<double> model_marginal; ///< P(realization) marginalised over parents
     double H; ///< entropy of the marginal
-    Gene_class gene_class; ///< gene class (VD_genes, DJ_genes, VJ_genes …)
+    Gene_class_legacy gene_class; ///< gene class (VD_genes, DJ_genes, VJ_genes …)
```
Comment (qmarcou) [inline tst/igor/entropy_test_helpers.h]: I'm not sure Gene_class style things should still exist here, may pose test maintenance issues

File: src/igor/Core/Hypermutationglobalerrorrate.cpp
Comment (qmarcou) [inline src/igor/Core/Hypermutationglobalerrorrate.cpp]: I get a lot of compiler warnings here
" In member function 'virtual void Hypermutation_global_errorrate::initialize(const Events_map&)':
/home/suquen/Nextcloud/Projects/dev/IGoR-immuno-stack/IGoR.worktrees/origin-feature-modelfileformat/src/igor/Core/Hypermutationglobalerrorrate.cpp:1546:22: warning: comparison between 'enum Gene_class_legacy' and 'enum Gene_class' [-Wenum-compare]
 1546 |         if (learn_on == V_gene | learn_on == VJ_genes | learn_on == VD_genes | learn_on == VDJ_genes) {"

File: src/igor/Core/Utils.h (hunk 1 above)
Comment (ErwanDemairy) [reply src/igor/Core/Utils.h:135]: The Gene_class now only contains V, D, J and undefined genes.
The Gene_class_legacy is the previous Gene_class.
But in some .cpp, the signature still use Gene_class_legacy, and it is unclear if (and how) it could be translated to Gene_class.

Not exhaustive, but the more meaningful:
- src/igor/Core/Rec_Event.cpp
```cpp
35:unordered_map<tuple<Event_type, Gene_class_legacy, Seq_side>, shared_ptr<Rec_Event>>
38:    unordered_map<tuple<Event_type, Gene_class_legacy, Seq_side>, shared_ptr<Rec_Event>> legacy_events_map;
45:        Gene_class_legacy gene_class = Undefined_gene_legacy;
```

- src/igor/Core/Hypermutationglobalerrorrate.cpp
```cpp
37:/*Hypermutation_global_errorrate::Hypermutation_global_errorrate(size_t nmer_width , Gene_class_legacy learn , Gene_class_legacy apply , double starting_flat_value): Error_rate() , mutation_Nmer_size(nmer_width) , learn_on(learn) , apply_to(apply) , ei_nucleotide_contributions((new double [4*nmer_width])) , R(starting_flat_value) , n_v_real(0) , n_j_real(0) , n_d_real(0) ,
47:Hypermutation_global_errorrate::Hypermutation_global_errorrate(size_t nmer_width, Gene_class_legacy learn, Gene_class_legacy apply,
172:Hypermutation_global_errorrate::Hypermutation_global_errorrate(size_t nmer_width, Gene_class_legacy learn, Gene_class_legacy apply,
183:                            "Hypermutation_global_errorrate(size_t,Gene_class_legacy,Gene_class_legacy,double,std::vector<double>)");
189:Hypermutation_global_errorrate::Hypermutation_global_errorrate(size_t nmer_width, Gene_class_legacy learn, Gene_class_legacy apply,
196:Hypermutation_global_errorrate::Hypermutation_global_errorrate(size_t nmer_width, Gene_class_legacy learn, Gene_class_legacy apply,
```

- src/igor/Core/HypermutationfullNmererrorrate.cpp
```cpp
35:Hypermutation_full_Nmer_errorrate::Hypermutation_full_Nmer_errorrate(size_t nmer_width, Gene_class_legacy learn,
36:                                                                     Gene_class_legacy apply, double starting_flat_value,
83:                            "symmetric) in Hypermutation_full_Nmer_errorrate(size_t nmer_width , Gene_class_legacy learn , "
84:                            "Gene_class_legacy apply , double starting_flat_value)");
93:                + " in Hypermutation_full_Nmer_errorrate(size_t nmer_width , Gene_class_legacy learn , Gene_class_legacy apply , "
156:Hypermutation_full_Nmer_errorrate::Hypermutation_full_Nmer_errorrate(size_t nmer_width, Gene_class_legacy learn,
157:                                                                     Gene_class_legacy apply,
170:                                       + " in Hypermutation_full_Nmer_errorrate(size_t nmer_width , Gene_class_legacy learn , "
171:                                         "Gene_class_legacy apply , vector<double> init_Nmer_mutations_probas)");
177:                "Hypermutation_full_Nmer_errorrate(size_t,Gene_class_legacy,Gene_class_legacy,double,std::vector<double>)");
181:Hypermutation_full_Nmer_errorrate::Hypermutation_full_Nmer_errorrate(size_t nmer_width, Gene_class_legacy learn,
182:                                                                     Gene_class_legacy apply, double starting_flat_value,
189:Hypermutation_full_Nmer_errorrate::Hypermutation_full_Nmer_errorrate(size_t nmer_width, Gene_class_legacy learn,
190:                                                                     Gene_class_legacy apply,
```

File: src/igor/Core/Deletion.cpp (hunk 2 above)
Comment (ErwanDemairy) [reply src/igor/Core/Deletion.cpp]: `Deletion::event_class` is set at construction time only. 
Added `const` in commit 770ea6a8f to its declaration to make its constness explicit.

File: src/igor/Core/Deletion.h (hunk 3 above)
Comment (ErwanDemairy) [reply src/igor/Core/Deletion.h]: Removed in commit 72f577cd39c905aa7b0b010f0309d240db5fbd0c .

File: src/igor/Core/Dinuclmarkov.cpp (hunk 4 above)
Comment (ErwanDemairy) [reply src/igor/Core/Dinuclmarkov.cpp]: Still relevant?

Comment (qmarcou) [reply src/igor/Core/Dinuclmarkov.cpp]: Nope, resolving

File: src/igor/Core/Hypermutationglobalerrorrate.cpp
Comment (ErwanDemairy) [reply src/igor/Core/Hypermutationglobalerrorrate.cpp]: Changed in commit de47f79a285173b62a1796e913f4c9f4387337a9 : since legacy and new gene values are different, they must not be compared.

File: src/igor/Core/Utils.h (hunk 1 above)
Comment (qmarcou) [reply src/igor/Core/Utils.h:135]: > 
> Not exhaustive, but the more meaningful:
> 
>     * src/igor/Core/Rec_Event.cpp
> 
> 
> ```c++
> 35:unordered_map<tuple<Event_type, Gene_class_legacy, Seq_side>, shared_ptr<Rec_Event>>
> 38:    unordered_map<tuple<Event_type, Gene_class_legacy, Seq_side>, shared_ptr<Rec_Event>> legacy_events_map;
> 45:        Gene_class_legacy gene_class = Undefined_gene_legacy;
> ```

This one was an adapter function for the other branch, should be moved to the migration file, but seems unused after integration in this branch. So delete or move to the temporary migration file until the end of migration.

Comment (qmarcou) [reply src/igor/Core/Utils.h:135]: The hypermutation models require a bit more rewiring, I think the `Gene_class_legacy` should in the end be refactored to a vector of `Seq_type`, but this requires rewriting some of the inner code, get rid of direct pointer access and make use of the introduced flanking `Seq_type` sequences.
I think this requires a dedicated fix/refactoring, and setting up proper unit tests for it. Could be deferred to a later stage of the refactoring.

**Review by qmarcou — COMMENTED** [review]
# Model file format v2.0 — Gene_class / Seq_type disambiguation

## Summary

This branch delivers two interdependent efforts that were originally separate
feature branches and got merged together once it became clear neither made
sense without the other:

1. **Gene_class / Seq_type separation** (#47 ) —
   disentangling genomic/alignment identity from constructed-sequence-segment
   identity throughout the event/inference/generation code.
2. **Model file format v2.0** (#46 ) —
   a backward-compatible extension of `*_parms.txt` that exposes that same
   distinction in the on-disk format.

Together they remove the ambiguity that previously made tandem-D models
impossible to represent, and are a prerequisite step towards the Tandem D
feature (#8), building on the dynamic `Seq_type` registry introduced in #15.

## Background: the problem

`Gene_class` had historically been used for two different concerns:
genomic/alignment identity (`V_gene`, `D_gene`, `J_gene`) *and*
constructed-sequence-segment/junction identity, via composite values
(`VD_genes`, `DJ_genes`, `VJ_genes`, `VDJ_genes`). For `Dinucl_markov` in
particular, a composite `Gene_class` value also acted as an implicit
surrogate for a `(Seq_type, Seq_side)` pair (e.g. `VD_genes` implicitly meant
"insert into `VD_ins_seq`, anchored on the `Five_prime` side"). This
conflation made the `events_map` key (`tuple<Event_type, Gene_class,
Seq_side>`) fundamentally unable to disambiguate tandem-D events, since two D
segments would collide on the same `Gene_class`, and left no way to express
a non-standard segment ordering in the model file.

## What changed

### Gene_class / Seq_type split

- **Narrower `Gene_class`, dynamic `Seq_type`.** `Gene_class` was pruned to
  `{V_gene, D_gene, J_gene, Undefined_gene}` — alignment identity only. The
  pre-refactor enum (with its composite `VD_genes`/`DJ_genes`/`VJ_genes`/
  `VDJ_genes` values) was kept as `Gene_class_legacy` for legacy-format I/O.
  `Seq_type` became a dynamic registry (`SeqTypeRegistry`) instead of a
  fixed 6-value enum, so it can represent arbitrary constructed-sequence
  layouts (e.g. tandem D segments).
- **Event classes now key off `Seq_type`.** `Rec_Event` and its subclasses
  (`Gene_choice`, `Deletion`, `Insertion`, `Dinucl_markov`, the error-rate
  and hypermutation models, and ancillary consumers like `Pgencounter` and
  `Coverage_err_counter`) were reworked to address constructed sequences via
  `Seq_type` rather than the old overloaded `Gene_class`, via bridge helpers
  (`try_gene_class_to_gene_seq_type`, `try_insertion_gene_class_to_seq_type`,
  `try_insertion_seq_type_to_gene_class`, `has_insertion_seq_type`,
  `try_get_event`) that were later centralized in `EventUtils` and a
  dedicated `gene_to_seqtype_migr` module, keeping legacy-format
  compatibility logic out of the core event classes. Genomic-identity checks
  (e.g. which alignments to explore) remain on `Gene_class`.
- **`Seq_type`-indexed events map for execution.** `Model_Parms` exposes a
  `Seq_type`-indexed view of the events map, and the execution context
  (`ModelContext`, `GenModel`) consumes only that typed map. The duplicated
  `iterate(...)`/`initialize_event(...)` legacy-map compatibility overloads
  that had crept into `Gene_choice`, `Deletion`, `Insertion`, and
  `Dinucl_markov` during implementation were removed and centralized once in the `Rec_Event` base
  class, and the `events_map` parameter was dropped from
  `compare_sequences_error_prob` across the `Error_rate` hierarchy.
- **Simplified `Dinucl_markov` traversal.** `DinuclTraversalSpec`/
  `Dinucl_markov` now use an explicit `(target Seq_type, anchor side)` pair
  instead of a separate traversal-side flag, since anchor side alone
  determines traversal direction, and walk the `Seq_type` ordering via
  `SeqTypeRegistry::get_left_neighbor`/`get_right_neighbor` instead of a
  hardcoded V→VD→D→DJ→J chain.

Two real regressions were found and fixed while restructuring insertion/
dinucleotide event lookup, and locked in with dedicated tests
(`test_EventUtils.cpp`):
- An incorrect cross-fallback where a VD insertion/dinucleotide event could
  fall back to the DJ event's matrix (and vice versa) instead of the shared
  `VDJ_genes` alias, now resolved with explicit, deterministic priority
  (specific key wins over the `VDJ` alias) instead of
  `unordered_map::emplace` order-dependent resolution.
- Shadowed member variables (`v_chosen`, `d_chosen`, `j_chosen`) in
  `Deletion::initialize_event`, and stale flag retention in
  `Genechoice::initialize_event` — both silently prevented state from being
  recomputed between iterations.

### Model file format v2.0

- New optional `@Version` / `@Seq_type_order` sections in `*_parms.txt`.
  Files without them are parsed as legacy v1.x; the `Seq_type` ordering is
  then inferred automatically from the events present.
- New v2.0 event declaration line: `#<event_type>;<gene_class>;<seq_type>;<seq_side>;<priority>;<nickname>`,
  adding an explicit `seq_type` field alongside the legacy `gene_class`.
- `Model_Parms` gained bidirectional read/write support: legacy files parse
  into the same internal representation as v2.0 files, and
  `requires_extended_format()` automatically selects the legacy writer for
  standard V(D)J/VJ models and the v2.0 writer for anything that doesn't fit
  the legacy `Gene_class`/ordering (e.g. tandem D). Marginals files are
  unchanged, since they only reference events by nickname.

### Testing
- New test suites covering the format v2 parser/writer round-trip
  (`tst/test_model_format_v2.cpp`, `tst/test_data/format_v2/*`, including
  legacy detection, v2 detection, tandem-D parms, invalid-gene-class
  rejection, and new-style edge names), `SeqTypeRegistry`/event-key
  conversion helpers (`tst/igor/Core/test_EventUtils.cpp`,
  `tst/igor/Core/test_Contexts.cpp`).

## Performance assessment

This feature has a very minor performance hit (if any) on the inference engine.
 
```
==================================================================
BENCHMARK SUMMARY - develop 5968ecb327fea
==================================================================
Context                        | Step                      | Time (s)   | Status
------------------------------------------------------------------
Pipeline (N=100, T=1)          | Generation                | 0.0782     | OK
Pipeline (N=100, T=1)          | Read Seqs                 | 0.0226     | OK
Pipeline (N=100, T=1)          | Alignment                 | 9.2055     | OK
Pipeline (N=100, T=1)          | Inference (2 iter)        | 1.8610     | OK
Pipeline (N=500, T=1)          | Generation                | 0.0952     | OK
Pipeline (N=500, T=1)          | Read Seqs                 | 0.0282     | OK
Pipeline (N=500, T=1)          | Alignment                 | 46.4668    | OK
Pipeline (N=500, T=1)          | Inference (2 iter)        | 8.2861     | OK
Pipeline (N=1000, T=1)         | Generation                | 0.0874     | OK
Pipeline (N=1000, T=1)         | Read Seqs                 | 0.0323     | OK
Pipeline (N=1000, T=1)         | Alignment                 | 89.4261    | OK
Pipeline (N=1000, T=1)         | Inference (2 iter)        | 16.3732    | OK
Pipeline (N=500, T=4)          | Generation                | 0.0886     | OK
Pipeline (N=500, T=4)          | Read Seqs                 | 0.0250     | OK
Pipeline (N=500, T=4)          | Alignment                 | 14.0119    | OK
Pipeline (N=500, T=4)          | Inference (2 iter)        | 3.0954     | OK
Pipeline (N=1000, T=4)         | Generation                | 0.0968     | OK
Pipeline (N=1000, T=4)         | Read Seqs                 | 0.0344     | OK
Pipeline (N=1000, T=4)         | Alignment                 | 29.8118    | OK
Pipeline (N=1000, T=4)         | Inference (2 iter)        | 5.5620     | OK
------------------------------------------------------------------

==================================================================
BENCHMARK SUMMARY - feature/modelfileformat d0d22479787338f162e2
==================================================================
Context                        | Step                      | Time (s)   | Status
------------------------------------------------------------------
Pipeline (N=100, T=1)          | Generation                | 0.0803     | OK
Pipeline (N=100, T=1)          | Read Seqs                 | 0.0331     | OK
Pipeline (N=100, T=1)          | Alignment                 | 10.9989    | OK
Pipeline (N=100, T=1)          | Inference (2 iter)        | 2.1249     | OK
Pipeline (N=500, T=1)          | Generation                | 0.0833     | OK
Pipeline (N=500, T=1)          | Read Seqs                 | 0.0270     | OK
Pipeline (N=500, T=1)          | Alignment                 | 47.8204    | OK
Pipeline (N=500, T=1)          | Inference (2 iter)        | 8.7909     | OK
Pipeline (N=1000, T=1)         | Generation                | 0.1203     | OK
Pipeline (N=1000, T=1)         | Read Seqs                 | 0.0418     | OK
Pipeline (N=1000, T=1)         | Alignment                 | 92.4088    | OK
Pipeline (N=1000, T=1)         | Inference (2 iter)        | 16.6042    | OK
Pipeline (N=500, T=4)          | Generation                | 0.0908     | OK
Pipeline (N=500, T=4)          | Read Seqs                 | 0.0275     | OK
Pipeline (N=500, T=4)          | Alignment                 | 13.7293    | OK
Pipeline (N=500, T=4)          | Inference (2 iter)        | 3.2713     | OK
Pipeline (N=1000, T=4)         | Generation                | 0.0973     | OK
Pipeline (N=1000, T=4)         | Read Seqs                 | 0.0388     | OK
Pipeline (N=1000, T=4)         | Alignment                 | 31.0885    | OK
Pipeline (N=1000, T=4)         | Inference (2 iter)        | 5.8058     | OK
------------------------------------------------------------------
```
## Remaining Implementation Refactoring

### Hypermutation models

Still use the `Gene_class_legacy` for implementation reasons.
Hypermutation models still require some refactoring to break the friend class requirement, access only constructed sequences, and use introduced flanking sequences instead of direct realization access via friendship.

See [here](https://github.com/IGoR-immuno-stack/IGoR/pull/59#discussion_r3386817424)

### Drop Seq_type information from Dinucl traversal specs
 Traversal specs currently still carry `Seq_type`, which should be removed once downstream consumers no longer need it.
See [here](https://github.com/IGoR-immuno-stack/IGoR/pull/53#discussion_r3358782649)

File: tst/igor/entropy_test_helpers.h (hunk 6 above)
Comment (qmarcou) [reply tst/igor/entropy_test_helpers.h]: Solved by 45c509520ee3de5c45f296cd84428c3e004879f0
